---
- hosts: slurm_client
  gather_facts: no  
  vars_files:
    - ./vars.yml 

  tasks:
 
 
  - name: make direcotry
    file:
      path: "/home/{{ superuser }}/.ssh"
      state: directory
   
  - name: create empty file
    file:
      path: "/home/{{ superuser }}/.ssh/authorized_keys"
      state: touch  
    
  - name: put pubkey
    lineinfile:
      path: "/home/{{ superuser }}/.ssh/authorized_keys"
      line: "{{ pubkey }}"
    
    
