---
- hosts: slurm_client
  #become: true

  vars_files:
    - ./vars.yml

  tasks:

          #- name: Run the equivalent of "apt-get update" as a separate step
          #apt:
          #update_cache: yes
          #become: yes
          #become_method: sudo

          #- name: Ensure required softwares are installed
          #apt:
          #name: "{{ pre_req_softwares }}"
          #state: present
           
    
          #- name: change munge folder as insecure
          #file:
          #path: /etc/munge/
          #owner: "{{ superuser }}"
          #group: "{{ superuser }}"
          #become: yes
          #become_method: sudo        


          #- name: delete newly installed munge key    
          #file:
          #path: /etc/munge/munge.key
          #state: absent
          #become: yes
          #become_method: sudo           

          #- name: copy munge key file to host
          #copy:
          #src: files/etc/munge/munge.key
          #dest: /etc/munge/munge.key
          #owner: munge
          #group: munge
          #mode: 0400
          #become: yes
          #become_method: sudo


          #- name: enable munge service 
          #service:
          #name: munge
          #enabled: yes
          #become: yes
          #become_method: sudo


          #- name: start munge service
          #service:
          #name: munge
          #state: started
          #ignore_errors: yes              
          #become: yes
          #become_method: sudo
  

          #- name: create storage directory
          #command: bash -lc "mkdir /storage"
          #become: yes
          #become_method: sudo


          #- name: change to storage directory and git clone
          #command: bash -lc "cd /storage && git clone https://github.com/mknoxnv/ubuntu-slurm.git"
          #become: yes
          #become_method: sudo


          #- name: install required tools
          #apt:
          #name: "{{ tools }}"
          #state: present
          #become: yes
          #become_method: sudo


          #- name: start slurm installation process
          #command: "{{ item }}"
          #args:
          #chdir: "/storage"
          #with_items:      
          #- "wget https://download.schedmd.com/slurm/slurm-17.11.12.tar.bz2"
          #- "tar xvjf slurm-17.11.12.tar.bz2"
          #become: yes
          #become_method: sudo  


          #- name: building slurm
          #command: "{{ item }}"
          #args:
          #chdir: "/storage/slurm-17.11.12"
          #with_items:
          #- "./configure --prefix=/tmp/slurm-build --sysconfdir=/etc/slurm --enable-pam --with-pam_dir=/lib/x86_64-linux-gnu/security/ --without-shared-libslurm"
          #- "make"
          #- "make contrib"
          #- "make install"
          #become: yes
          #become_method: sudo


          #- name: install fpm
          #command: bash -lc "gem install fpm"
          #become: yes
          #become_method: sudo


          #- name: slurm initialization
          #command: "{{ item }}"
          #args:
          #chdir: "/storage"
          #with_items:
          #- "fpm -s dir -t deb -v 1.0 -n slurm-17.11.12 --prefix=/usr -C /tmp/slurm-build ."      
          #- "dpkg -i slurm-17.11.12_1.0_amd64.deb"
          #- "mkdir /etc/slurm"
          #become: yes
          #become_method: sudo


          #- name: slurm initialization
          #command: "{{ item }}"
          #with_items:
          #- "cp /storage/ubuntu-slurm/slurm.conf /etc/slurm/"
          #- "cp /storage/ubuntu-slurm/gres.conf /etc/slurm/gres.conf"
          #- "cp /storage/ubuntu-slurm/cgroup.conf /etc/slurm/cgroup.conf"
          #- "cp /storage/ubuntu-slurm/cgroup_allowed_devices_file.conf /etc/slurm/cgroup_allowed_devices_file.conf"
          #become: yes
          #become_method: sudo


          #- name: Add the user 'slurm'
          #user:
          #name: slurm
          #become: yes
          #become_method: sudo


          #- name: copy slurmd service
          #copy:
          #src: /storage/ubuntu-slurm/slurmd.service
          #dest: /etc/systemd/system
          #become: yes
          #become_method: sudo


          #- name: Change munge folder ownership,
          #file:
          #path: /etc/munge/
          #mode: 755
          #become: yes
          #become_method: sudo


          #- name: enable slurmd service
          #service:
          #name: slurmd
          #enabled: yes
          #become: yes
          #become_method: sudo            


          #- name: start slurmd service
          #service:
          #name: slurmd
          #state: started
          #become: yes
          #become_method: sudo



  - name: copy the cookie
    shell: "slurmd -C"
    register: nodeinfo
    become: yes
    become_method: sudo

  - name : Copy cookie to empty file
    shell: echo "{{ nodeinfo.stdout }}" > ./nodeinfo.properties
    delegate_to: 127.0.0.1
    become: yes
    become_method: sudo 


  - name: Adding configuration
    lineinfile:
      dest: /etc/redis/redis.conf
      state: present
      regexp: '^bind 127.0.0.1'
      line: '#bind 127.0.0.1'
    become: yes
    become_method: sudo

  



  #  - name: install required  
  #  apt:
  #    name: "{{ item }}"
  #    state: present



  - hosts: slurm_master
    tasks: 

    #- name: change munge key as insecure file
    #file:
    #   path: /etc/munge/
    #   owner: "{{ superuser }"
    #   group: "{{ superuser }}" 
    #   mode: 755

  #  - name: change munge key as insecure file
  # file:
  #    path: /etc/munge/munge.key
  #    owner: "{{ superuser }"
  #    group: "{{ superuser }}"
  #    mode: 700
  
  #- name: configure munge
  #  copy: 
  #     src: files/etc/munge/munge.key 
  #     dest: /etc/munge/munge.key
  #     owner: munge 
  #     group: munge 
  #     mode: 0400
        
                    

  #- name: change munge key as insecure file
  #  file:
  #     path: /etc/munge/
  #     owner: "{{ superuser }"
  #     group: "{{ superuser }}"
       

